name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Artifact Directory
        run: mkdir -p SampleArtifact

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed

      - name: Install Newman and Reporters
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run API Tests
        run: newman run "Collection/Simform_gorest_API_collection.json" -e "Collection/Simform_gorest_environment.json" -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html
        continue-on-error: true  # Optional: Prevents stopping the workflow on test failures

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: API-test-report
          path: SampleArtifact
